export const WORD_HINTS = {
  ALBUM: [
    "A collection of music or photos.",
    "Often stored digitally or on a CD.",
  ],
  HINGE: [
    "Allows doors to open and close.",
    "A metaphor for a pivotal moment.",
  ],
  MONEY: ["Used to purchase goods or services.", "Comes in coins and bills."],
  SCRAP: ["A small leftover piece of material.", "A minor fight or dispute."],
  GAMER: [
    "Someone who plays video games.",
    "Often found using a console or PC.",
  ],
  GLASS: [
    "A transparent material used in windows.",
    "Can also refer to a drinking vessel.",
  ],
  SCOUR: ["To clean something intensely.", "To search thoroughly."],
  BEING: ["The state of existing.", "Can refer to a living creature."],
  DELVE: ["To dig or investigate deeply.", "Often used in research contexts."],
  YIELD: ["To produce or give way.", "Also a traffic sign indicating caution."],
  METAL: [
    "A hard, shiny material like iron or gold.",
    "Often used in construction and tools.",
  ],
  TIPSY: ["Slightly intoxicated.", "Unsteady or wobbly."],
  SLUNG: ["Thrown or hung loosely.", "Past tense of 'sling'."],
  FARCE: [
    "A comedic play with exaggerated characters.",
    "A situation so absurd it’s laughable.",
  ],
  GECKO: ["A small climbing lizard.", "Known for its sticky toe pads."],
  SHINE: ["To emit light or glow.", "What shoes do after polishing."],
  CANNY: ["Shrewd or clever in business.", "Carefully calculating."],
  MIDST: ["In the middle of something.", "Often used in formal writing."],
  BADGE: ["A symbol of rank or achievement.", "Worn by police or scouts."],
  HOMER: ["A home run in baseball.", "Also the name of a famous Greek poet."],
  TRAIN: [
    "A series of connected railroad cars.",
    "To teach or improve skills.",
  ],
  STORY: ["A narrative of events.", "Can refer to a floor in a building."],
  HAIRY: ["Covered with hair.", "Describes a scary or intense situation."],
  FORGO: ["To do without something.", "To refrain from an indulgence."],
  LARVA: ["An immature form of an insect.", "Stage between egg and adult."],
  TRASH: ["Waste material or garbage.", "Can also mean to criticize harshly."],
  SHOWN: ["Past tense of show.", "Displayed or presented."],
  HEIST: ["A robbery or theft.", "Often planned and dramatic."],
  ASKEW: ["Not in a straight position.", "Crooked or tilted."],
  INERT: ["Lacking ability to move.", "Chemically inactive."],
  OLIVE: ["A small green or black fruit.", "Also a color name."],
  PLANT: [
    "A living organism that grows in soil.",
    "Can also mean to place something firmly.",
  ],
  OXIDE: [
    "A compound of oxygen and another element.",
    "Common in rust or corrosion.",
  ],
  CARGO: ["Goods transported by ship or plane.", "Freight or load."],
  FOYER: ["An entrance hall in a building.", "Used as a waiting area."],
  FLAIR: ["A natural talent or style.", "Also refers to decorative badges."],
  AMPLE: ["More than enough.", "Generously sufficient in amount."],
  CHEEK: [
    "Part of the face below the eye.",
    "Can also mean boldness or impudence.",
  ],
  SHAME: ["A painful feeling of guilt.", "A cause of regret or embarrassment."],
  MINCE: ["To chop into small pieces.", "To speak in an affected way."],
  CHUNK: ["A thick solid piece.", "A significant amount of something."],
  ROYAL: ["Related to a king or queen.", "Noble or majestic."],
  SQUAD: [
    "A small group of people working together.",
    "Common in military or sports.",
  ],
  BLACK: ["The darkest color.", "Can also refer to mourning or secrecy."],
  STAIR: [
    "A step in a set leading upward or downward.",
    "Used to move between floors.",
  ],
  SCARE: ["To frighten someone.", "A sudden fear or alarm."],
  FORAY: ["A sudden attack or raid.", "A first attempt at a new activity."],
  COMMA: ["A punctuation mark.", "Used to separate items in a list."],
  NATAL: ["Relating to birth.", "Associated with the place of origin."],
  SHAWL: [
    "A piece of cloth worn over shoulders.",
    "Often used for warmth or modesty.",
  ],
  FEWER: ["Smaller in number.", "The opposite of 'more'."],
  TROPE: [
    "A common theme or device in storytelling.",
    "Often seen in movies or literature.",
  ],
  SNOUT: ["A long projecting nose.", "Typical in pigs and dogs."],
  LOWLY: ["Humble or of low rank.", "Not important or powerful."],
  STOVE: ["Used to cook food.", "Typically found in kitchens."],
  SHALL: ["A formal word for 'will'.", "Used in legal or old-style speech."],
  FOUND: ["Discovered something lost.", "Also the past tense of 'find'."],
  NYMPH: ["A mythical nature spirit.", "Also a young stage of an insect."],
  EPOXY: ["A strong adhesive or resin.", "Used for bonding materials."],
  DEPOT: [
    "A place for storing goods or buses.",
    "A transportation or military facility.",
  ],
  CHEST: ["A box for storage.", "Also a part of the human body."],
  PURGE: [
    "To cleanse or get rid of.",
    "Can refer to removal of people or toxins.",
  ],
  SLOSH: ["To splash around liquid.", "Describes messy, watery movement."],
  THEIR: ["Possessive form of 'they'.", "Used to indicate ownership."],
  RENEW: ["To restore or refresh.", "Often used for subscriptions."],
  ALLOW: ["To give permission.", "To enable something to happen."],
  SAUTE: [
    "To cook quickly in a small amount of fat.",
    "Common in pan-frying vegetables or meat.",
  ],
  MOVIE: ["A motion picture.", "Watched in cinemas or at home."],
  CATER: ["To provide food and service.", "Often done for events or parties."],
  TEASE: ["To make fun of someone playfully.", "To provoke or tempt."],
  SMELT: ["To extract metal from ore.", "Also a type of small fish."],
  FOCUS: ["Concentration on a subject.", "Also a setting on a camera."],
  TODAY: ["The present day.", "Refers to the current date."],
  WATCH: ["A time-telling device.", "Also means to observe attentively."],
  LAPSE: ["A temporary failure or break.", "Can refer to time passing."],
  MONTH: ["A unit of time, about 30 days.", "There are 12 in a year."],
  SWEET: ["Sugary in taste.", "Also a term of endearment."],
  HOARD: [
    "To accumulate and store secretly.",
    "Often done with valuable items.",
  ],
  CLOTH: ["A piece of fabric.", "Used in clothing or cleaning."],
  BRINE: ["Salt water solution.", "Used for pickling or curing."],
  AHEAD: ["In front or forward.", "Also means in the future."],
  MOURN: ["To express grief.", "Often done after a loss."],
  NASTY: ["Unpleasant or offensive.", "Can describe attitude or condition."],
  RUPEE: ["Currency of India.", "Has different denominations."],
  CHOKE: ["To have trouble breathing.", "Also means to block."],
  CHANT: ["A repetitive song or shout.", "Used in protests or rituals."],
  SPILL: ["To accidentally drop liquid.", "Can also refer to a secret leak."],
  VIVID: ["Bright and colorful.", "Also means clear and detailed."],
  BLOKE: ["British slang for a man.", "Informal and friendly term."],
  TROVE: ["A collection of valuable items.", "Often used with 'treasure'."],
  THORN: ["A sharp plant point.", "Found on roses or bushes."],
  OTHER: ["Different or additional.", "Not this one, but another."],
  TACIT: ["Unspoken but understood.", "Implied without being stated."],
  SWILL: [
    "Drink greedily or in large amounts.",
    "Also refers to low-quality food or drink.",
  ],
  DODGE: [
    "To avoid something quickly.",
    "Can refer to evasive movement or tactics.",
  ],
  SHAKE: ["To move back and forth quickly.", "Also a kind of drink."],
  CAULK: ["To seal joints or seams.", "Used in construction to block leaks."],
  AROMA: ["A pleasant smell.", "Often used with food or coffee."],
  CYNIC: [
    "A person who doubts others' sincerity.",
    "Believes people are motivated by self-interest.",
  ],
  ROBIN: [
    "A small bird with a red breast.",
    "Common in North America and Europe.",
  ],
  ULTRA: [
    "Beyond the usual or extreme.",
    "Often used to describe high-performance products.",
  ],
  ULCER: [
    "A sore on the skin or stomach lining.",
    "Can cause pain and discomfort.",
  ],
  PAUSE: ["A temporary stop.", "Commonly used in music or videos."],
  HUMOR: [
    "The quality of being funny.",
    "Also refers to mood or bodily fluid in old medicine.",
  ],
  FRAME: [
    "A structure supporting or enclosing something.",
    "Also refers to a single image in a video.",
  ],
  ELDER: ["An older person.", "Also means higher in age or status."],
  SKILL: ["The ability to do something well.", "Can be learned or innate."],
  ALOFT: ["Up in the air.", "Often used with flying objects."],
  PLEAT: ["A fold in fabric.", "Used in clothing for style or fit."],
  SHARD: ["A broken piece of glass or pottery.", "Sharp and dangerous."],
  MOIST: ["Slightly wet.", "Often used in baking or weather."],
  THOSE: ["Plural of 'that'.", "Refers to specific things or people."],
  LIGHT: [
    "Electromagnetic radiation visible to the eye.",
    "Also means not heavy.",
  ],
  WRUNG: ["Past tense of 'wring'.", "Means twisted or squeezed."],
  COULD: ["Expresses possibility or ability.", "A past form of 'can'."],
  PERKY: ["Lively and cheerful.", "Often describes a personality."],
  MOUNT: ["To climb or ascend.", "Also a support or platform."],
  WHACK: ["To hit hard.", "Also means a loud strike."],
  SUGAR: ["A sweet substance.", "Used in cooking and baking."],
  KNOLL: ["A small, rounded hill.", "Often found in landscapes."],
  CRIMP: ["To fold or press into ridges.", "Used in metal or hair styling."],
  WINCE: ["To flinch in pain or distress.", "An involuntary reaction."],
  PRICK: ["A small sharp pain.", "Also to pierce slightly."],
  ROBOT: ["A machine that performs tasks.", "Often programmable or automated."],
  POINT: ["A sharp end or a position.", "Used to express ideas or aim."],
  PROXY: [
    "A substitute or representative.",
    "Often used in voting or internet terms.",
  ],
  SHIRE: ["A rural English county.", "Used historically in England."],
  SOLAR: ["Related to the sun.", "Used in renewable energy context."],
  PANIC: ["Sudden overwhelming fear.", "Can lead to irrational behavior."],
  TANGY: ["A sharp, zesty flavor.", "Often used to describe citrus."],
  ABBEY: ["A monastery or convent.", "Often a large, old religious building."],
  FAVOR: ["An act of kindness.", "Also means to prefer."],
  DRINK: ["A liquid for consumption.", "Can be water, juice, or alcohol."],
  QUERY: ["A question or request for info.", "Common in databases or emails."],
  GORGE: ["A narrow valley between hills.", "Also means to eat greedily."],
  CRANK: [
    "A handle that turns a machine.",
    "Also a term for an eccentric person.",
  ],
  SLUMP: ["A sudden fall or drop.", "Can refer to posture or economy."],
  BANAL: ["Lacking originality.", "Boring due to overuse."],
  TIGER: ["A large striped cat.", "Top predator in the wild."],
  SIEGE: ["A military blockade.", "Used to force surrender."],
  TRUSS: ["A support structure.", "Used in bridges and buildings."],
  BOOST: ["To increase or lift up.", "Used in morale or performance."],
  REBUS: [
    "A puzzle using pictures or symbols.",
    "Represents words or parts of words.",
  ],
  UNIFY: ["To bring together.", "To make into a whole."],
  TROLL: ["To provoke online.", "Also a mythical creature."],
  TAPIR: [
    "A herbivorous mammal with a trunk.",
    "Native to South America and Asia.",
  ],
  ASIDE: ["To the side.", "Also a remark not meant to be heard."],
  FERRY: [
    "A boat for transporting people or vehicles.",
    "Used to cross water.",
  ],
  ACUTE: ["Sharp or severe in effect.", "Also describes angles less than 90°."],
  PICKY: ["Hard to please.", "Selective about choices."],
  WEARY: ["Tired or exhausted.", "Resulting from hard work or stress."],
  GRIPE: ["To complain persistently.", "Also means a minor complaint."],
  CRAZE: ["A popular trend or fad.", "Often short-lived and intense."],
  PLUCK: ["To pull something quickly.", "Also means courage or bravery."],
  BRAKE: ["Used to stop a vehicle.", "Found in cars and bikes."],
  BATON: [
    "A stick used by a conductor or police.",
    "Also used in relay races.",
  ],
  CHAMP: ["To chew noisily.", "Short for 'champion'."],
  PEACH: ["A sweet, juicy fruit.", "Has fuzzy skin and a pit."],
  USING: ["Employing something for a task.", "The act of utilizing resources."],
  TRACE: ["A small amount.", "Also means to outline or follow."],
  VITAL: ["Extremely important or necessary.", "Also means essential to life."],
  SONIC: ["Related to sound.", "Also the name of a fast hedgehog."],
  MASSE: ["A billiards shot.", "Involves curving the cue ball."],
  CONIC: ["Shaped like a cone.", "Related to geometry."],
  VIRAL: [
    "Spreading quickly, especially online.",
    "Can also refer to infections.",
  ],
  RHINO: ["A large horned animal.", "Short for rhinoceros."],
  BREAK: ["To separate into pieces.", "Also a short rest."],
  TRIAD: ["A group of three.", "Also refers to Chinese secret societies."],
  EPOCH: ["A period in history.", "Marked by notable events."],
  USHER: ["Someone who shows seats.", "Also means to guide or lead in."],
  EXULT: ["To rejoice greatly.", "To show extreme happiness."],
  GRIME: ["Dirt or soot.", "Often hard to clean."],
  CHEAT: ["To act dishonestly.", "Common in games and tests."],
  SOLVE: ["To find the answer.", "Often used in math or puzzles."],
  BRING: ["To carry or deliver.", "To cause something to happen."],
  PROVE: ["To demonstrate the truth.", "Often used in arguments or science."],
  STORE: ["A place to buy items.", "Also means to keep or save."],
  TILDE: ["A punctuation mark (~).", "Used in languages and math."],
  CLOCK: ["Tells the time.", "Can be analog or digital."],
  WROTE: ["Past tense of 'write'.", "Created text or a document."],
  RETCH: ["To gag or vomit.", "A reflex from nausea."],
  PERCH: ["A spot to rest or sit.", "Also a type of fish."],
  ROUGE: ["A red makeup.", "Applied to cheeks or lips."],
  RADIO: ["A device for audio broadcasts.", "Uses electromagnetic waves."],
  SURER: ["More certain or confident.", "Comparative of 'sure'."],
  FINER: ["Of higher quality.", "Comparative of 'fine'."],
  VODKA: ["A strong alcoholic drink.", "Common in Eastern Europe."],
  HERON: ["A long-legged bird.", "Found near water."],
  CHILL: ["Cold or relaxed state.", "Also means to calm down."],
  GAUDY: ["Too bright or showy.", "Lacking good taste."],
  PITHY: ["Short but full of meaning.", "Concise and expressive."],
  SMART: ["Intelligent or well-dressed.", "Can also mean a stinging pain."],
  BADLY: ["In a poor manner.", "Opposite of 'well'."],
  ROGUE: ["A dishonest person.", "Also used for misbehaving animals."],
  GROUP: [
    "A number of people or things together.",
    "Often organized with a purpose.",
  ],
  FIXER: [
    "Someone who solves problems.",
    "Can also mean someone arranging shady deals.",
  ],
  GROIN: ["Area between abdomen and thigh.", "Sensitive part of the body."],
  DUCHY: [
    "Territory ruled by a duke or duchess.",
    "Found in some European countries.",
  ],
  COAST: ["Land along a sea.", "Also means to move without power."],
  BLURT: ["To say something suddenly.", "Often without thinking."],
  PULPY: ["Soft and juicy like fruit.", "Can describe texture or books."],
  ALTAR: ["A sacred table used in worship.", "Common in churches and temples."],
  GREAT: ["Very good or large in size.", "Can describe quality or fame."],
  BRIAR: ["A thorny plant or shrub.", "Also a type of smoking pipe."],
  CLICK: ["A short, sharp sound.", "Also used for mouse actions."],
  GOUGE: ["To dig or force out.", "Can also mean to overcharge."],
  WORLD: ["The Earth or all people.", "Can refer to a domain or sphere."],
  ERODE: ["To wear away slowly.", "Often caused by wind or water."],
  BOOZY: ["Affected by alcohol.", "Informally means slightly drunk."],
  DOZEN: ["A group of twelve.", "Common unit in baking or eggs."],
  FLING: ["To throw with force.", "Also a short romantic affair."],
  GROWL: ["A deep threatening sound.", "Made by dogs or angry people."],
  ABYSS: ["A deep chasm or void.", "Symbolic for something unfathomable."],
  STEED: ["A horse, often heroic.", "Used in medieval or poetic terms."],
  ENEMA: [
    "A fluid injection for cleansing.",
    "Used in medical or health contexts.",
  ],
  JAUNT: ["A short pleasant trip.", "Often for leisure or fun."],
  COMET: ["A celestial object with a tail.", "Made of ice and dust."],
  TWEED: ["A rough woolen fabric.", "Popular in jackets and suits."],
  PILOT: ["A person who flies planes.", "Also a test version of something."],
  DUTCH: ["Relating to the Netherlands.", "Also a shared payment method."],
  BELCH: ["To release gas from the stomach.", "Often loud and impolite."],
  OUGHT: ["Indicates duty or correctness.", "Similar to 'should'."],
  DOWRY: ["Property given at marriage.", "Traditionally from bride’s family."],
  THUMB: ["The short, thick finger.", "Important for gripping."],
  HYPER: ["Overactive or energetic.", "Short for hyperactive."],
  HATCH: ["To come out of an egg.", "Also a small door or opening."],
  ALONE: ["By oneself, without others.", "Can also mean lonely."],
  MOTOR: ["An engine that produces motion.", "Found in vehicles and machines."],
  ABACK: ["By surprise or shock.", "Usually used with 'taken'."],
  GUILD: ["An organization of craftsmen.", "Often from medieval times."],
  KEBAB: ["Grilled meat on a skewer.", "Popular in Middle Eastern cuisine."],
  SPEND: ["To use money or time.", "Often related to expenses."],
  FJORD: ["A deep sea inlet.", "Found in Norway and similar places."],
  ESSAY: ["A short written work.", "Often gives personal views."],
  SPRAY: ["A fine mist of liquid.", "Used in cleaning or cosmetics."],
  SPICY: [
    "Having a strong flavor or heat.",
    "Common in Indian and Mexican foods.",
  ],
  AGATE: ["A type of colored stone.", "Often used in jewelry."],
  SALAD: ["A cold dish with vegetables.", "Can include dressing and meat."],
  BASIC: ["Fundamental or simple.", "The starting level or core."],
  MOULT: ["To shed feathers or skin.", "Common in birds and reptiles."],
  CORNY: ["Overused or cheesy.", "Lacking originality or freshness."],
  FORGE: ["To make metal objects.", "Also to create something fake."],
  CIVIC: ["Relating to a city or citizens.", "Used in duties or pride."],
  ISLET: ["A small island.", "Smaller than an isle."],
  LABOR: ["Work, especially physical.", "Also used in childbirth."],
  GAMMA: ["A Greek letter.", "Also used in rays or radiation."],
  LYING: ["Not telling the truth.", "Also means reclining."],
  AUDIT: [
    "An official inspection of accounts.",
    "Used in business or education.",
  ],
  ROUND: ["Shaped like a circle.", "A stage in a game or competition."],
  LOOPY: ["Full of loops or crazy.", "Can mean eccentric or silly."],
  LUSTY: ["Full of strength or desire.", "Often implies vigor or appetite."],
  GOLEM: ["A creature of clay in folklore.", "Used in fantasy or myth."],
  GONER: ["Someone beyond help.", "Slang for someone doomed."],
  GREET: ["To say hello.", "A common form of welcome."],
  START: ["To begin something.", "Also a sudden movement."],
  LAPEL: ["Part of a jacket or coat.", "Folded back on the chest."],
  BIOME: [
    "A natural community of flora and fauna.",
    "Examples: desert, forest, tundra.",
  ],
  PARRY: ["To block or deflect an attack.", "Used in fencing or arguments."],
  SHRUB: ["A small woody plant.", "Smaller than a tree."],
  FRONT: ["The forward-facing side.", "Also a weather term."],
  WOOER: ["One who courts another.", "Often in romantic pursuit."],
  TOTEM: ["A symbolic tribal object.", "Often carved or worshipped."],
  FLICK: ["A quick light movement.", "Also slang for a movie."],
  DELTA: ["A river mouth landform.", "Also a Greek letter."],
  BLEED: ["To lose blood.", "Can also mean to drain resources."],
  ARGUE: ["To have a disagreement.", "Also means to present reasons."],
  SWIRL: ["To move in a circular pattern.", "Often seen in water or wind."],
  ERROR: ["A mistake or flaw.", "Common in programming or judgment."],
  AGREE: ["To have the same opinion.", "To consent to something."],
  OFFAL: ["Animal organs used as food.", "Considered waste by some."],
  FLUME: ["A water channel or slide.", "Found in amusement parks or mills."],
  CRASS: [
    "Lacking sensitivity or refinement.",
    "Often describes rude behavior.",
  ],
  PANEL: ["A flat section or board.", "Also a group of people."],
  STOUT: ["Thick and strong.", "Also a type of dark beer."],
  BRIBE: [
    "Money or favor given for influence.",
    "Used to gain unfair advantage.",
  ],
  DRAIN: ["To remove liquid.", "Also means to exhaust energy."],
  YEARN: ["To long deeply for something.", "Often emotional or romantic."],
  PRINT: ["To produce text or images.", "Also a newspaper or photo copy."],
  SEEDY: ["Run-down or shabby.", "Also full of seeds."],
  IVORY: ["A white material from tusks.", "Also a shade of white."],
  BELLY: ["The stomach area.", "Can also mean to swell."],
  STAND: ["To be upright on feet.", "Also means to tolerate."],
  FIRST: ["Comes before all others.", "Also a beginning or priority."],
  FORTH: ["Moving out or forward.", "Often paired with 'back'."],
  BOOBY: ["A silly person.", "Also a type of bird."],
  FLESH: ["Soft tissue of the body.", "Between skin and bones."],
  UNMET: ["Not fulfilled or satisfied.", "As in unmet expectations."],
  LINEN: ["Fabric made from flax.", "Used for sheets or clothes."],
  MAXIM: ["A short statement of truth.", "A proverb or saying."],
  POUND: ["A unit of weight.", "Also to hit repeatedly."],
  MIMIC: ["To imitate or copy.", "Often done for humor."],
  SPIKE: ["A sharp pointed object.", "Also a sudden increase."],
  CLUCK: ["The sound a chicken makes.", "Also used to express concern."],
  CRATE: ["A large wooden box.", "Used for storage or shipping."],
  DIGIT: ["A single number.", "Also a finger or toe."],
  REPAY: ["To return money or favor.", "The opposite of borrowing."],
  SOWER: ["One who plants seeds.", "Related to farming or parables."],
  CRAZY: ["Mentally wild or silly.", "Also means extremely enthusiastic."],
  ADOBE: [
    "A building material made from clay.",
    "Also the name of a software company.",
  ],
  OUTDO: ["To perform better than someone.", "Means to surpass or excel."],
  TRAWL: ["To fish with a large net.", "Also means to search thoroughly."],
  WHELP: ["A young dog.", "Can also mean to give birth (animals)."],
  UNFED: ["Not given food.", "Describes a hungry state."],
  PAPER: [
    "Material for writing or printing.",
    "Also means an academic article.",
  ],
  STAFF: ["A group of employees.", "Also a stick for support or authority."],
  CROAK: ["A hoarse sound, like a frog.", "Also slang for dying."],
  HELIX: ["A spiral shape.", "The shape of DNA."],
  FLOSS: ["Used for cleaning teeth.", "Also thin thread or string."],
  PRIDE: ["A feeling of self-respect.", "Also a group of lions."],
  BATTY: ["Slightly crazy or eccentric.", "Colloquial term for being silly."],
  REACT: ["To respond to a stimulus.", "Also a popular JavaScript library."],
  MARRY: ["To join in marriage.", "Also means to combine two things."],
  ABASE: ["To degrade or belittle.", "To lower in rank or prestige."],
  COLON: ["A punctuation mark.", "Also a part of the intestine."],
  STOOL: ["A seat without a back.", "Also a bowel movement (medical)."],
  CRUST: ["The outer layer of bread or earth.", "Crunchy surface layer."],
  FRESH: ["Recently made or obtained.", "Also means energetic or new."],
  DEATH: ["The end of life.", "Opposite of birth."],
  MAJOR: ["Greater in size or importance.", "Also a military rank."],
  FEIGN: ["To pretend or fake.", "To give a false impression."],
  ABATE: ["To lessen in intensity.", "Commonly used with storms or pain."],
  BENCH: ["A long seat.", "Also used in sports or law."],
  QUIET: ["Without noise.", "Can also describe a reserved person."],
  GRADE: ["A mark for academic work.", "Also a level of quality."],
  STINK: ["To smell bad.", "Also means to be very unpleasant."],
  KARMA: ["The result of one's actions.", "A concept from Indian religions."],
  MODEL: [
    "A representation or example.",
    "Also a person who showcases clothing.",
  ],
  DWARF: ["A small mythical creature.", "Also means to overshadow something."],
  HEATH: ["An open uncultivated land.", "Also a type of shrubland."],
  SERVE: ["To provide a service or food.", "Also used in tennis."],
  NAVAL: ["Relating to a navy.", "Involves ships and military."],
  EVADE: ["To escape or avoid.", "Often used with questions or danger."],
  FOCAL: ["Central or important.", "Related to focus or vision."],
  BLUSH: ["To turn red from embarrassment.", "Also a cosmetic product."],
  AWAKE: ["Not asleep.", "To become alert or conscious."],
  HUMPH: ["An exclamation of annoyance.", "Often used to express disapproval."],
  SISSY: [
    "An offensive term for a timid person.",
    "Used to describe someone not brave.",
  ],
  REBUT: ["To argue against.", "To provide a counterargument."],
  CIGAR: ["Rolled tobacco for smoking.", "Thicker than a cigarette."],
};
